spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka

logging:
  level:
    #org.apache.coyote.http11: debug
    com.example.userserivce: DEBUG # 디버그 모드 부터 출력

# actuator end 포인트
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, env

token:
 expiration-time: 86400012 # ms단위 60*60*24 * 1000 = 하루
 secret: ecommerce-token # 토큰이 만들어질 때 반영됨