spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 매번 새로운 값으로 인식하기위해 헤더값 초기화
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} # 서비스단에서 prefix 없애기
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users #회원가입
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} # 서비스단에서 prefix 없애기
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/** # 다른 GET방식 메서드들
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} # 서비스단에서 prefix 없애기
            - AuthorizationHeaderFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/** # 다른 GET방식 메서드들
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} # 서비스단에서 prefix 없애기
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
        - id: first-service
          uri: lb://MY-FIRST-SERVICE # 이동할 주소
          predicates:
            - Path=/first-service/** # 사용자가 입력한 주소
          filters:
#            - AddRequestHeader=first-request, first-requests-header2 # AddRequestHeader 하고 = 붙혀야함..
#            - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second-request, second-requests-header2
#            - AddResponseHeader=second-response, second-response-header2
            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: Spring Cloud Gateway Logging Filter
#                preLogger: true
#                postLogger: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true